# Generated by Django 5.1.2 on 2024-12-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ex", "0003_rename_dir_limitorder_direction_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="limitorder",
            name="filled_quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="marketorder",
            name="filled_quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="stoporder",
            name="filled_quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="takeorder",
            name="filled_quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="triggerorder",
            name="filled_quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="limitorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("INITIATED", "Initiated"),
                    ("PLACED", "Placed"),
                    ("FILLED", "Filled"),
                    ("REJECTED", "Rejected"),
                    ("CANCELED", "Canceled"),
                    ("ERROR", "Error"),
                ],
                default="INITIATED",
            ),
        ),
        migrations.AlterField(
            model_name="marketorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("INITIATED", "Initiated"),
                    ("PLACED", "Placed"),
                    ("FILLED", "Filled"),
                    ("REJECTED", "Rejected"),
                    ("CANCELED", "Canceled"),
                    ("ERROR", "Error"),
                ],
                default="INITIATED",
            ),
        ),
        migrations.AlterField(
            model_name="stoporder",
            name="status",
            field=models.CharField(
                choices=[
                    ("INITIATED", "Initiated"),
                    ("PLACED", "Placed"),
                    ("FILLED", "Filled"),
                    ("REJECTED", "Rejected"),
                    ("CANCELED", "Canceled"),
                    ("ERROR", "Error"),
                ],
                default="INITIATED",
            ),
        ),
        migrations.AlterField(
            model_name="takeorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("INITIATED", "Initiated"),
                    ("PLACED", "Placed"),
                    ("FILLED", "Filled"),
                    ("REJECTED", "Rejected"),
                    ("CANCELED", "Canceled"),
                    ("ERROR", "Error"),
                ],
                default="INITIATED",
            ),
        ),
        migrations.AlterField(
            model_name="triggerorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("INITIATED", "Initiated"),
                    ("PLACED", "Placed"),
                    ("FILLED", "Filled"),
                    ("REJECTED", "Rejected"),
                    ("CANCELED", "Canceled"),
                    ("ERROR", "Error"),
                ],
                default="INITIATED",
            ),
        ),
    ]
