# Generated by Django 5.1.2 on 2024-12-10 16:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ex", "0004_limitorder_filled_quantity_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="limitorder",
            old_name="filled_quantity",
            new_name="initial_quantity",
        ),
        migrations.RenameField(
            model_name="marketorder",
            old_name="filled_quantity",
            new_name="initial_quantity",
        ),
        migrations.RenameField(
            model_name="stoporder",
            old_name="filled_quantity",
            new_name="initial_quantity",
        ),
        migrations.RenameField(
            model_name="takeorder",
            old_name="filled_quantity",
            new_name="initial_quantity",
        ),
        migrations.RenameField(
            model_name="triggerorder",
            old_name="filled_quantity",
            new_name="initial_quantity",
        ),
    ]
