# Generated by Django 5.1.2 on 2024-12-10 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ex", "0005_rename_filled_quantity_limitorder_initial_quantity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="limitorder",
            name="is_init",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="marketorder",
            name="is_init",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="stoporder",
            name="is_init",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="takeorder",
            name="is_init",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="triggerorder",
            name="is_init",
            field=models.BooleanField(default=False),
        ),
    ]
