# Generated by Django 5.1.2 on 2024-12-28 10:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ex", "0007_remove_symbol_best_ask_remove_symbol_best_bid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="depo",
            name="is_init",
        ),
    ]
